[package]
name = "ndk-glue"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Startup code for android binaries"
license = "MIT OR Apache-2.0"

[dependencies]
android_log-sys = "0.1.2"
ndk = { path = "../ndk", version = "0.1" }
ndk-sys = { path = "../ndk-sys", version = "0.1" }
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
